AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API REST using AWS Lambda and DynamoDB with Python

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  FetchAllUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python-api/src/
      Handler: app.fetch_all_users
      Events:
        FetchAllUsers:
          Type: Api
          Properties:
            Path: /FetchAllUsers
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python-api/src/
      Handler: app.create_user
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /CreateUser
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  UpdateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python-api/src/
      Handler: app.update_user
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /UpdateUser/{id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python-api/src/
      Handler: app.delete_user
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /DeleteUser/{id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: usersDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "URL API REST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
